CREATE TABLE dept03(
    deptno VARCHAR(03),
    dname VARCHAR(07)
);

ALTER TABLE dept03
ADD (area VARCHAR(20));

SELECT * FROM DEPT03;

ALTER TABLE dept03
MODIFY dname VARCHAR(20);

SELECT * FROM DEPT03;

ALTER TABLE dept03
ADD CONSTRAINT PK_DEPTNO PRIMARY KEY(deptno);

CREATE TABLE emp03(
    empno VARCHAR2(04),
    name  VARCHAR2(20),
    deptno VARCHAR2(03) NOT NULL,
    pempno VARCHAR2(4),
    pay NUMBER NOT NULL,
    position VARCHAR(20),
    regdate VARCHAR(20),
    CONSTRAINT PK_EMPNO PRIMARY KEY(empno)
);

COMMENT ON COLUMN emp03.empno IS '사원코드';
COMMENT ON COLUMN emp03.name IS '사원이름';
COMMENT ON COLUMN emp03.deptno IS '부서코드';
COMMENT ON COLUMN emp03.pempno IS '상사코드';
COMMENT ON COLUMN emp03.pay IS '급여';
COMMENT ON COLUMN emp03.position IS '직급';
COMMENT ON COLUMN emp03.regdate IS '등록일';

commit;


INSERT INTO dept03(deptno, dname)
VALUES(101, '영업부');
INSERT INTO dept03(deptno, dname)
VALUES(102, '총무부');
INSERT INTO dept03(deptno, dname)
VALUES(103, '기획부');
INSERT INTO dept03(deptno, dname)
VALUES(104, '홍보부');

commit;

CREATE SEQUENCE SEQ_EMP03_EMPNO
INCREMENT BY 1
START WITH 1001;

INSERT INTO EMP03(EMPNO, NAME, DEPTNO, PEMPNO, PAY, POSITION, REGDATE)
VALUES(SEQ_EMP03_EMPNO.NEXTVAL, '가가가', 101, NULL, 450, '부장', SYSDATE);

INSERT INTO EMP03(EMPNO, NAME, DEPTNO, PEMPNO, PAY, POSITION, REGDATE)
VALUES(SEQ_EMP03_EMPNO.NEXTVAL, '나나나', 102, NULL, 400, '부장', SYSDATE);

INSERT INTO EMP03(EMPNO, NAME, DEPTNO, PEMPNO, PAY, POSITION, REGDATE)
VALUES(SEQ_EMP03_EMPNO.NEXTVAL, '다다다', 101, NULL, 350, '과장', SYSDATE);

INSERT INTO EMP03(EMPNO, NAME, DEPTNO, PEMPNO, PAY, POSITION, REGDATE)
VALUES(SEQ_EMP03_EMPNO.NEXTVAL, '라라라', 103, NULL, 410, '과장', SYSDATE);

INSERT INTO EMP03(EMPNO, NAME, DEPTNO, PEMPNO, PAY, POSITION, REGDATE)
VALUES(SEQ_EMP03_EMPNO.NEXTVAL, '마마마', 101, 1003, 300, '대리', SYSDATE);


INSERT INTO EMP03(EMPNO, NAME, DEPTNO, PEMPNO, PAY, POSITION, REGDATE)
VALUES(SEQ_EMP03_EMPNO.NEXTVAL, '바바바', 103, NULL, 400, '대리', SYSDATE);

INSERT INTO EMP03(EMPNO, NAME, DEPTNO, PEMPNO, PAY, POSITION, REGDATE)
VALUES(SEQ_EMP03_EMPNO.NEXTVAL, '가나다', 102, 1002, 320, '대리', SYSDATE);

INSERT INTO EMP03(EMPNO, NAME, DEPTNO, PEMPNO, PAY, POSITION, REGDATE)
VALUES(SEQ_EMP03_EMPNO.NEXTVAL, '홍길동', 102, 1007, 380, '사원', SYSDATE);

INSERT INTO EMP03(EMPNO, NAME, DEPTNO, PEMPNO, PAY, POSITION, REGDATE)
VALUES(SEQ_EMP03_EMPNO.NEXTVAL, '강감찬', 103, 1006, 250, '사원', SYSDATE);

INSERT INTO EMP03(EMPNO, NAME, DEPTNO, PEMPNO, PAY, POSITION, REGDATE)
VALUES(SEQ_EMP03_EMPNO.NEXTVAL, '이순신', 101, 1005, 200, '사원', SYSDATE);


UPDATE dept03
SET
AREA = '서울'
WHERE DNAME = '영업부';

DELETE FROM EMP03
WHERE DEPTNO = 101;

ROLLBACK;

SELECT NAME, POSITION, EMPNO
FROM EMP03
ORDER BY EMPNO ASC;

SELECT SEQ_EMP03_EMPNO.NEXTVAL FROM EMP03;












